remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-minimal
title: <h1>Hi there, I'm <a href="https://spbmolot.github.io/spbmolot/" target="_blank">Anton</a>
  <img src="https://github.com/blackcater/blackcater/raw/main/images/Hi.gif" height="32"/></h1>
description: <h3>Netology student, Python-developer from Russia [Telegram](https://t.me/tonymolotilo/), [LinkedIn](https://t.me/tonymolotilo/), [Twitter](https://img.shields.io/badge/Twitter-blue?style=for-the-badge&logo=twitter&logoColor=white/)</h3>
